services:
  whisper-api:
    build: ./api
    container_name: whisper_api
    networks:
      - web
    volumes:
      - whisper_data:/app/data
    # Exponieren des Ports intern (Traefik nutzt den Service-Port, kein direkter Host-Port nötig)
    environment:
      - CUDA_AVAILABLE=0
      - REGISTRATION_KEY=12345
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper-api.rule=Host(`whisper-api.shape-z.de`)"
      - "traefik.http.routers.whisper-api.entrypoints=websecure"
      - "traefik.http.routers.whisper-api.tls=true"
      - "traefik.http.routers.whisper-api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.whisper-api.loadbalancer.server.port=5000"

  whisper-web:
    build: ./frontend
    container_name: whisper_web
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper-web.rule=Host(`whisper.shape-z.de`)"
      - "traefik.http.routers.whisper-web.middlewares=security@file"
      - "traefik.http.routers.whisper-web.tls=true"
      - "traefik.http.routers.whisper-web.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.whisper-web.entrypoints=websecure"
      - "traefik.http.services.whisper-web.loadbalancer.server.port=3000"

networks:
  web:
    external: true

volumes:
  whisper_data:


